{{- if .Values.ssh.enabled }}
{{- range $nameSuffix, $pubkey := .Values.ssh.pubkeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubevirt-vm.fullname" $ }}-sshkey-{{ $nameSuffix }}
  labels:
    {{- include "kubevirt-vm.labels" $ | nindent 4 }}
    sshkey: {{ $nameSuffix }}
data:
  id_rsa.pub: {{ $pubkey | b64enc }}
{{- end }}
{{- end }}
